[package]
name = "git-swift"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.20.0"
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version="1.0.217", features = ["derive"] }
serde_json = "1.0.135"
# tokio = { version = "1.43.0", features = ["full"] }
